### ISSUE TITLE
Protein file is not found at runtime

### ISSUE THREAD

**Issue by suryasaha** [AgBase/kobas#1]
https://github.com/AgBase/kobas/blob/a7d335926ac18dbe30f8299cd2e859688aca91d8/wrapper.sh#L110

See error below
```
docker run --rm -v /home/surya/seq_pep:/seq_pep -v /home/surya/sqlite3:/sqlite3 -v $(pwd):/work-dir agbase/kobas:3.0.3_0 -a -i upreg.names.faa -s dme -t fasta:pro -o def -T 64
Building a new DB, current time: 04/23/2020 17:35:03
New DB name:   /work-dir/seq_pep/dme.pep.fasta
New DB title:  seq_pep/dme.pep.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File seq_pep/dme.pep.fasta does not exist
BLAST Database error: No alias or index file found for protein database [seq_pep/dme.pep.fasta] in search path [/work-dir::]
```

**Comment by suryasaha** [comment]
Wrapper script looks for the seq_pep.tar.gz and sqlite.tar.gz files in working directory. So two options:
- start from seq_pep.tar.gz and sqlite3.tar.gz  in your working directory each time you run it
- untar both files and mount the directories with -v

Getting files from DE ```/iplant/home/shared/iplantcollaborative/protein_blast_dbs/kobas```

**Comment by suryasaha** [comment]
Needs .TAR files in workdir.
Why do we need to mount seq_pep and sqlite3 if it copies files from .TAR files?

**Comment by suryasaha** [comment]
Get file using anonymous WebDAV
https://data.cyverse.org/dav-anon/iplant/commons/community_released/iplantcollaborative/protein_blast_dbs/kobas.

**Comment by amcooksey** [comment]
new version pulls the necessary files based on species abbreviation.
